#!/usr/bin/perl -w
use strict;

my $str = 'ADXBTC   ARNBTC     BNBBTC   CDTBTC   DOCKBTC  GASBTC  ICXBTC   LENDBTC  MDABTC   NCASHBTC  ONTBTC   PPTBTC   RLCBTC    STORJBTC  USDCBTC   WPRBTC  YOYOBTC AEBTC    ASTBTC     BNTBTC   CNDBTC   EDOBTC   GNTBTC  INSBTC   LINKBTC  MFTBTC   NEOBTC    PAXBTC   QKCBTC   RVNBTC    STORMBTC  VETBTC    WTCBTC  ZECBTC AGIBTC   BATBTC     BQXBTC   CVCBTC   ENGBTC   GOBTC   IOSTBTC  LOOMBTC  MITHBTC  NPXSBTC   PHXBTC   QLCBTC   SCBTC     SYSBTC    VIABTC    XEMBTC  ZENBTC AIONBTC  BCDBTC     BRDBTC   DASHBTC  ENJBTC   GRSBTC  IOTABTC  LRCBTC   MTHBTC   NULSBTC   PIVXBTC  QSPBTC   SKYBTC    THETABTC  VIBBTC    XLMBTC  ZILBTC AMBBTC   BCHABCBTC  BTCUSDT  DCRBTC   ETCBTC   GTOBTC  IOTXBTC  LSKBTC   MTLBTC   NXSBTC    POABTC   QTUMBTC  SNGLSBTC  TNBBTC    VIBEBTC   XMRBTC  ZRXBTC APPCBTC  BCHSVBTC   BTGBTC   DGDBTC   EVXBTC   GVTBTC  KEYBTC   LTCBTC   NANOBTC  OAXBTC    POEBTC   RENBTC   SNMBTC    TNTBTC    WABIBTC   XRPBTC ARDRBTC  BCPTBTC    BTSBTC   DLTBTC   FUELBTC  HCBTC   KMDBTC   LUNBTC   NASBTC   OMGBTC    POLYBTC  REPBTC   SNTBTC    TRXBTC    WANBTC    XVGBTC ARKBTC   BLZBTC     BTTBTC   DNTBTC   FUNBTC   HOTBTC  KNCBTC   MCOBTC   NAVBTC   ONGBTC    POWRBTC  REQBTC   STEEMBTC  TUSDBTC   WAVESBTC  XZCBTC';
$str = 'ADABTC  CMTBTC  DATABTC  DENTBTC  ELFBTC  EOSBTC  ETHBTC  GXSBTC  MANABTC  NEBLBTC  OSTBTC  RCNBTC  RDNBTC  STRATBTC';
$str = 'ADABTC   ASTBTC     BRDBTC   DATABTC  ENJBTC  GRSBTC   IOTXBTC  LUNBTC   NCASHBTC  PHXBTC   QTUMBTC  SNGLSBTC  TUSDBTC   XEMBTC   ZRXBTC
ADXBTC   BATBTC     BTGBTC   DCRBTC   EOSBTC  GTOBTC   KEYBTC   MANABTC  NEBLBTC   PIVXBTC  RCNBTC   SNMBTC    VETBTC    XLMBTC 
AEBTC    BCDBTC     BTSBTC   DENTBTC  ETCBTC  GVTBTC   KMDBTC   MCOBTC   NEOBTC    POABTC   RDNBTC   STEEMBTC  VIABTC    XMRBTC 
AGIBTC   BCHABCBTC  BTTBTC   DGDBTC   ETHBTC  GXSBTC   KNCBTC   MDABTC   NPXSBTC   POEBTC   RENBTC   STORJBTC  VIBBTC    XRPBTC
AIONBTC  BCHSVBTC   CDTBTC   DLTBTC   EVXBTC  HCBTC    LENDBTC  MFTBTC   NULSBTC   POLYBTC  REPBTC   STORMBTC  VIBEBTC   XVGBTC
AMBBTC   BCPTBTC    CELRBTC  DNTBTC   FETBTC  HOTBTC   LINKBTC  MITHBTC  OAXBTC    POWRBTC  REQBTC   STRATBTC  WABIBTC   XZCBTC
APPCBTC  BLZBTC     CMTBTC   DOCKBTC  FUNBTC  ICXBTC   LOOMBTC  MTHBTC   OMGBTC    PPTBTC   RLCBTC   SYSBTC    WANBTC    YOYOBTC
ARDRBTC  BNBBTC     CNDBTC   EDOBTC   GASBTC  INSBTC   LRCBTC   MTLBTC   ONGBTC    QKCBTC   RVNBTC   TNBBTC    WAVESBTC  ZECBTC
ARKBTC   BNTBTC     CVCBTC   ELFBTC   GNTBTC  IOSTBTC  LSKBTC   NANOBTC  ONTBTC    QLCBTC   SCBTC    TNTBTC    WPRBTC    ZENBTC
ARNBTC   BQXBTC     DASHBTC  ENGBTC   GOBTC   IOTABTC  LTCBTC   NASBTC   OSTBTC    QSPBTC   SKYBTC   TRXBTC    WTCBTC    ZILBTC';


my @marts = split(/\s+/, $str);
print "{ '" . join("':1, '", @marts) . "':1 }\n";

